In [2]:
import numpy as np


In [3]:
x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [9]:
# ndarray from tuple
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


* create matrix in numpy
* in numpy,we use the np.array() function otcreate a matrix. for example,


In [5]:
#create a 2x2 matrix
matrix1=np.array([[1,3],[5,7]])
print("2x2 matrix:\n",matrix1)

2x2 matrix:
 [[1 3]
 [5 7]]


In [6]:
#create 3x3 matrix
matrix2= np.array([[2,3,5],[4,5,6],[23,45,59]])
print("\n 3x3 matrix:\n", matrix2)


 3x3 matrix:
 [[ 2  3  5]
 [ 4  5  6]
 [23 45 59]]


In [7]:
a=np.array([[2,3,4],[7,8,9],
            [2,3,45]])
print(a)
print()
b= np.array([[2,3,4],[7,12,34],[45,68,7]])
print(b)
print()
c=a+b
print(c)


[[ 2  3  4]
 [ 7  8  9]
 [ 2  3 45]]

[[ 2  3  4]
 [ 7 12 34]
 [45 68  7]]

[[ 4  6  8]
 [14 20 43]
 [47 71 52]]
