# shallow copy and deep copy

In [52]:
l=[1,"2",3,4,5]
l1=l
l1

[1, '2', 3, 4, 5]

In [53]:
l1[2]=100
l1

[1, '2', 100, 4, 5]

In [54]:
l

[1, '2', 100, 4, 5]

In [55]:
l2=l.copy()
l2[1]=100
l2

[1, 100, 100, 4, 5]

In [56]:
print(l)
l2

[1, '2', 100, 4, 5]


[1, 100, 100, 4, 5]

In [57]:
print(id(l),id(l2))

1700902276288 1700902280448


In [58]:
L=[[1,2,3],[4,56]]
L

[[1, 2, 3], [4, 56]]

In [59]:
L2=L.copy()
L2

[[1, 2, 3], [4, 56]]

In [103]:
l2

[1, 100, 100, 4, 5]

In [102]:
L

[[1, 2, 3], [4, 56]]

In [61]:
import copy

In [62]:
l=[[1,2,3],[4,5,6]]
L2=copy.deepcopy(l)
l2

[1, 100, 100, 4, 5]

In [63]:
L2[0][2]=100
print(L2)
print(l)

[[1, 2, 100], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]


# random number generation
* as discussed earlier , we use the random module to work with random numbers in numpy.


In [64]:
import numpy as np

In [65]:
# generate random integer from 0 to 9
randomnumber=np.random.randint(0,10)
print(randomnumber)

1


In [66]:
from numpy import random
randomnumber=random.randint(0,10)
print(randomnumber)

7


# generate random float in numpy
* we can also generate random floating - point number between 0-1. for that we use the random.rand() function. for example,

In [67]:
randomnumber=np.random.rand()
print(randomnumber)

0.567715788220597


# generate random array in numpy 
* numpy's random module can also be used to generate an array of random numbers.

In [68]:
# generate 1d array of 5 random numbers between 0-1
floatarray =np.random.rand(5)
print("1d random float array:\n",floatarray)

1d random float array:
 [0.45137772 0.8752461  0.84948206 0.56203274 0.641447  ]


In [69]:
# generate 2d array of shape (3,4) with random integers
result=np.random.randint(0,10,(3,4))
print("random integer array\n",result)

random integer array
 [[5 2 4 4]
 [7 6 2 3]
 [0 1 0 5]]


In [70]:
# create an array of integer from 1 to 5
array1 = np.array([1,2,3,4,5])

In [71]:
# choose a random number from array1
randomchoice=np.random.choice(array1)
print(randomchoice)

3


* number from normal distribution with zero mean and standard deviation 1 i.e. standard deviation

In [72]:
np.random.randn(5,5)

array([[ 2.03334204,  1.04948652, -1.18133019, -1.05202642,  0.8185578 ],
       [ 1.76371694, -0.36789782,  0.90919047, -0.22421927, -1.97226011],
       [-1.15282144,  0.57467233,  0.25188985, -0.02186307, -0.56359089],
       [ 0.0107299 ,  0.36291229,  0.80223518, -1.24092702, -0.23204471],
       [-0.40171519,  0.89062995, -0.20614035, -0.63273209,  0.89366461]])

In [73]:
import numpy as np
from numpy.random import randint as ri

In [74]:
#np.random.seed(100)

In [75]:
np.random.seed(6)
ri(1,100,(5,6))

array([[11, 74, 85, 80, 81, 63],
       [26,  2, 76, 78, 58, 27],
       [34, 69, 34,  9,  3, 77],
       [85, 92, 32, 67,  6, 27],
       [16, 90, 87, 44, 70, 50]])

In [76]:
np.random.seed(244)
m=ri(1,100,25).reshape(5,5)
m

array([[27,  9, 73,  8, 92],
       [27, 15, 11, 38, 68],
       [41,  4, 27,  4, 28],
       [11, 25, 27, 83, 98],
       [89, 60, 50, 37, 93]])

In [77]:
np.sort(m)

array([[ 8,  9, 27, 73, 92],
       [11, 15, 27, 38, 68],
       [ 4,  4, 27, 28, 41],
       [11, 25, 27, 83, 98],
       [37, 50, 60, 89, 93]])

In [78]:
np.sort(m, axis=0)

array([[11,  4, 11,  4, 28],
       [27,  9, 27,  8, 68],
       [27, 15, 27, 37, 92],
       [41, 25, 50, 38, 93],
       [89, 60, 73, 83, 98]])

In [79]:
a=ri(1,100,30)
b=a.reshape(6,5)
b

array([[87, 98,  3, 58, 87],
       [27,  9, 82,  6, 60],
       [17,  6, 43, 94, 13],
       [69, 82, 59,  3,  1],
       [18, 70, 85,  6, 25],
       [85,  8, 83, 46, 15]])

In [80]:
a

array([87, 98,  3, 58, 87, 27,  9, 82,  6, 60, 17,  6, 43, 94, 13, 69, 82,
       59,  3,  1, 18, 70, 85,  6, 25, 85,  8, 83, 46, 15])

In [81]:
a.max()

98

In [82]:
a.min()

1

In [83]:
a.argmax()

1

In [84]:
ls=[121,23,34,45,56]
a=np.array(ls)
a.argsort()

array([1, 2, 3, 4, 0], dtype=int64)

In [85]:
b.argmax()

1

In [86]:
b.argmax(axis=1)

array([1, 2, 3, 1, 2, 0], dtype=int64)

In [87]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [88]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [89]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [90]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
a[a%2 !=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [93]:
a[a==5]

array([5])

In [94]:
a[a<5]

array([1, 2, 3, 4])

In [95]:
a[a%2 !=0]=0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [96]:
np.where(a==3)

(array([], dtype=int64),)

In [97]:
b=np.array([1,2,3,4,5,6])
print(b)

[1 2 3 4 5 6]


In [101]:
np.where(b>4)

(array([4, 5], dtype=int64),)