In [60]:
import numpy as np


* perform matrix multiplication in numpy
* we use the np.dot() function to perform multipiation between two mayrices.
* the number of column of first matrix and the number of rows of seconf=d matrix then multiplication is possible.

In [61]:
# create two matrices
matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])
#calculate the dot product of the two mayrices
result=np.dot(matrix1,matrix2)
print("mayrix1 x matrix2: \n" , result)
# 1 3               2 6                 1*2+2*6              1*6+3*8
# 5 7               4 8

mayrix1 x matrix2: 
 [[14 30]
 [38 86]]


In [62]:
# CREATE a matrix
matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()

[[1 3]
 [5 7]]



In [63]:
#get transose of matrix1
result=np.transpose(matrix1)
print(result)

[[1 5]
 [3 7]]


# numpy.hstack()function
* horizontally stack numpy array using numpy.hstack()

In [64]:
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
print(np.hstack((x,y)))

[3 5 7]

[5 7 9]

[3 5 7 5 7 9]


In [65]:
x=np.array([[3],[5],[7]])
print(x)
print("----")
y=np.array([[5],[7],[9]])
print(y)
print("----")
print(np.hstack((x,y)))

[[3]
 [5]
 [7]]
----
[[5]
 [7]
 [9]]
----
[[3 5]
 [5 7]
 [7 9]]


In [66]:
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
print(np.vstack((x,y)))

[3 5 7]

[5 7 9]

[[3 5 7]
 [5 7 9]]


In [67]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.vstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3]
 [5]
 [7]
 [5]
 [7]
 [9]]


# numpy.arange
* this function returns an ndarray object containing evenly spaced values within a given range.
# an array of evenly spaced numbers 


In [68]:
 a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [69]:
# this is ine dimensional array
a= np.arange(24)
a.ndim

1

In [70]:
x=np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [71]:
#start and stop parameter set
import numpy as np
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


# numpy.linspace
* this function is similar to arange() function.in this function, instead of step size,the number of evenly spaced values between the interval is specified.

In [72]:
x=np.linspace(10,18,5)
print(x)

[10. 12. 14. 16. 18.]


In [73]:
# endpoint set to false
import numpy as np
x=np.linspace(10,20,5, endpoint=False) # 10 12 14 16 18
print(x)

[10. 12. 14. 16. 18.]


In [74]:
# find retstep value
x=np.linspace(1,2,5,retstep=True)
print(x)
# retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [75]:
a=np.array([[3,3,2],[6,7,8],[5,6,7]])
print(a)

[[3 3 2]
 [6 7 8]
 [5 6 7]]


In [76]:
a.shape

(3, 3)

In [77]:
np.sum(a)

47

In [78]:
np.sum(a,axis=0) # column

array([14, 16, 17])

In [79]:
np.sum(a,axis=1) # row

array([ 8, 21, 18])

In [80]:
np.min(a)

2

In [81]:
np.max(a)

8

In [82]:
np.max(a,axis=1)

array([3, 8, 7])

In [83]:
np.max(a,axis=0)

array([6, 7, 8])

In [84]:
np.min(a,axis=0)

array([3, 3, 2])

In [85]:
np.min(a,axis=1)

array([2, 6, 5])