# NUMPY

* numpy is the fundamental package for scientific compouunding in python .it is a python liabrary that provides a multidimensional array object, various derived objects(such masked arrays and matrices), and an assortment of routines for fast operations on array ,including mathematical,logical,shape manupilation,sorting,selecting,i\o,discrete fourier transforms basic linear algebra,basic statistical operation ,random stiulation and much more.


* collection of similar type of element

# NUMPY ndARRAY

* NDARRAY IS THE N- DIMENSIONAL ARRAY OBJECT DEFINED IN THE NUMPY WHICH STORES THE COLLECTION OF THE SIMILAR TYPE OF THE DATA TYPE (DTYPE) OBJECTS.
* THE NDARRAY OBJECT CAN BE ACCESSSED BY USING THE 0 BASED INDEXING. EACH ELEMENT OF THE ARRAY OBJECT CONTAINS THE SAME SIZE INT HE MEMORY.


In [2]:
import numpy as np 
a= np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
import numpy as np 
a= np.array([1,2,'a'])
print(a)

['1' '2' 'a']


In [4]:
import numpy as np 
a= np.array([1,2.5,'a'])
print(a)

['1' '2.5' 'a']


In [5]:
#sring------"upcasting"
#float
#int

In [6]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [8]:
a=np.array([1,2,3],dtype=complex)#a+jb
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [9]:
a=np.array([1.0,2.0,3.0],dtype=int)
print(a)

[1 2 3]


# ndarray.shape
* this array attribute returns a tuple consdering of array dimensions. It can also be used to resize the array.

In [10]:
A= np.array([[1,2,3],[4,5,6]])
print(A)
print()
print(A.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [11]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


# reshape
* numpy also provides a reshape function to resize an array.

In [12]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


# zero funtion
* returns a new array of specified size and type, filled with zeroes.
* numpy.zeroes() 

In [25]:
x=np.zeros((5),dtype=int)
print(x)

[0 0 0 0 0]


# ones function
* returns a new array of specified size and type, filled with ones.
* array of five ones. default dtype is float.

In [14]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [15]:
x=np.zeros([2,2],dtype=int)
print(x)


[[0 0]
 [0 0]]


In [16]:
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [17]:
a.ndim

2

In [18]:
a.shape

(2, 3)

In [19]:
a.size

6

In [20]:
x=2*(np.ones(5))
print(x)

[2. 2. 2. 2. 2.]


In [28]:
y=np.eye(5) # identity matrix
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
x=np.array([[12,23,34],[34,45,56],[67,78,89]])
print(x)
y=np.diag(x)
print()
print(y)

[[12 23 34]
 [34 45 56]
 [67 78 89]]

[12 45 89]


In [23]:
x=np.diag([2,3,4,5,6])
print(x)

[[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]


# ASARRAY
* this function issimilar to numpy.array except for the fact that it has fewer parameters. this routine is useful for converting python sequence into ndarray.

In [24]:
x=[1,2,3] 
print(type(x))
a=np.asarray(x)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
