In [110]:
import numpy as np

In [111]:
x=np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
#even number
np.where(x%2==0)

(array([1, 3, 5, 7], dtype=int64),)

In [113]:
# odd number
np.where(x%2!=0)


(array([0, 2, 4, 6], dtype=int64),)

In [114]:
# search sorted
x=np.array([1,2,3,4,5,6,710])
print(x)

[  1   2   3   4   5   6 710]


In [115]:
np.searchsorted(x,4)

3

# indexing and slicing-2d array

In [116]:
x=np.array([[1,2,3,4,10],[12,23,34,56,6],[34,4,56,78,89],[11,22,33,44,55],[66,77,88,99,90]])
x

array([[ 1,  2,  3,  4, 10],
       [12, 23, 34, 56,  6],
       [34,  4, 56, 78, 89],
       [11, 22, 33, 44, 55],
       [66, 77, 88, 99, 90]])

In [117]:
x[1:3,1:3]

array([[23, 34],
       [ 4, 56]])

In [118]:
x[2:4,2:4]

array([[56, 78],
       [33, 44]])

# comparison between list and array
* three benefits of array
* takes less memory
* convininent
* fast


In [119]:
import sys
import time




sys.getsizeof(100)

28

In [120]:
# memory
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [121]:
import numpy as np


In [122]:
a=np.arange(200000)
print(a.itemsize)
print()
print(a.itemsize*len(a))

4

800000


In [123]:
#fast

In [124]:
a1=range(1000000)
b1=range(1000000)
start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken :",(time.time()-start)*1000)


time taken : 877.8963088989258


In [125]:
a2=np.arange(1000000)
b2=np.arange(1000000)
start=time.time()
c2=a2+b2
print("time taken by array",(time.time()-start)*1000)

time taken by array 5.002260208129883


In [126]:
#convininent

In [127]:
n1=np.arange(100)
n2=np.arange(100)

In [128]:
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [129]:
#list(range(5))

In [130]:
a.shape

(200000,)

In [131]:
b=a.reshape(2,4,3)
b
#b.ravel()

ValueError: cannot reshape array of size 200000 into shape (2,4,3)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[6,7]])
#np.concatenate((a,b))

In [ ]:
a


In [ ]:
b

In [ ]:
np.concatenate((a,b),axis=0)# axis=0 means rows

In [ ]:
np.concatenate((a,b),axis=1)# axis=1 means column

In [ ]:
a=np.arange(12)
np.split(a,3)

In [ ]:
a=np.array([[1,2,3],[4,5,6,]])
np.append(a,[7,8,9])